name: Build & Publish to NPM

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pnpm install

      - name: Build source
        run: pnpm build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  publish-npm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: dist

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
